//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int Importance { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Email { get; set; }
    }
}
